---
- name: create snapper directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: '755'
  loop:
    - "/etc/snapper/config-templates/"

- name: create snapper templates
  ansible.builtin.template:
    src: snapper-config.j2
    dest: "/etc/snapper/config-templates/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
    lstrip_blocks: true
  vars:
    cfg: "{{ item.value }}"
  with_dict: "{{ snapper_templates }}"

- name: include configuration creation tasks
  ansible.builtin.include_tasks: create_config.yml
  loop: "{{ snapper_configs }}"
  loop_control:
    loop_var: config

- name: include configuration deletion tasks
  ansible.builtin.include_tasks: delete_config.yml
  loop: "{{ snapper_configs_absent }}"
  loop_control:
    loop_var: config_name
